### ISSUE TITLE
Tests failing on Geosupport 18d

### ISSUE THREAD

**Issue by ishiland** [ishiland/python-geosupport#11]
Tests are failing for [Geosupport 18D](https://ci.appveyor.com/project/ishiland/python-geosupport/build/job/hs4eio3j4d3kqy7n). This appears to be due to Geosupport data changes not matching the expected test value.  

It seems one approach would be to write data-agnostic unit tests, but not sure that is the right direction and/or possible.

**Comment by docmarionum1** [comment]
I fixed it for now so the tests will pass, but I agree I'm not sure what the best way to handle it is going forward.

We want to make sure that the data coming out is being parsed correctly, which means we need to care about specific values.  For instance, in this case if the work area were expanded and the location of that field were changed, we would want the tests to fail, which necessarily means testing the values coming out and making sure they're being mapped to the correct place.

I wonder if the geosupport developers have any dummy data in there that they use to test it and ensure forward compatibility.  

I'm going to close this and open a new issue regarding more generally the possibility of data-agnostic testing.
