### ISSUE TITLE
g.address() method for house_number and  street_name together (i.e. freeform)?

### ISSUE THREAD

**Issue by myidealab** [ishiland/python-geosupport#12]
Is there an argument for the g.address() method that allows the input to include both house_number and street_name to be part of one variable? In the desktop version, it is referred to as freeform.

Thanks for the assistance.

**Comment by docmarionum1** [comment]
@myidealab You can put both into the `street` argument. For example:

```
g.address(street='125 worth st', borough='MN')
g.address(street='123-01 Roosevelt Ave', borough='QU')
```
