### ISSUE TITLE
how to use the browse flag

### ISSUE THREAD

**Issue by SPTKL** [ishiland/python-geosupport#15]
hi there,

I would like to use browse flag for picking primary addresses, but I don't know the syntax for it, can you provide more info how to use it?> 

Thanks

**Comment by docmarionum1** [comment]
See this page:

https://nycplanning.github.io/Geosupport-UPG/chapters/chapterIII/section08/

In python-geosupport it can be called like:

```python
>> from geosupport import Geosupport
>> g = Geosupport()
>> g['1B']({'borough': 'MN', 'street': '2019 A C Powell blvd', 'Browse Flag': 'P'})['First Street Name Normalized']
'7 AVENUE'
>> g['1B']({'borough': 'MN', 'street': '2019 A C Powell blvd', 'Browse Flag': 'F'})['First Street Name Normalized']
'ADAM CLAYTON POWELL JR BOULEVARD'
```

**Comment by SPTKL** [comment]
What's the syntax for using it like 
```g['1B'](borough_code='MN', house_number='120', street_name='Broadway')```

**Comment by docmarionum1** [comment]
I added support for that:

```python
g['1B'](borough_code='MN', house_number='120', street_name='Broadway', browse_flag='F')
```

**Comment by SPTKL** [comment]
Thank you so much

**Comment by SPTKL** [comment]
Can you also push the update to pypi.org? thanks, very grateful for this package

**Comment by ishiland** [comment]
@SPTKL just uploaded to pypi. @docmarionum1 thanks for the commit!
