### ISSUE TITLE
Zip Code inconsistancies between input and output

### ISSUE THREAD

**Issue by SPTKL** [ishiland/python-geosupport#18]
just an observation here I noticed that when geocoding using zipcode, the output zipcode is not always the same as the input zipcode, any idea why this is happening? 
```
>>>geo=g['1b'](house_number='33-33', street_name='broadway', zip_code='10031')
>>>geo.get('ZIP Code', '')
'10006'
```
In this case, the house number 33-33 has display format 33, and 33 Broadway is indeed in lower Manhattan with a zipcode 10006. 

So I started thinking if it's because geosupport translates zipcode to borough, then geocode. so I tried to use a brooklyn zipcode 11238 to see if it's still returning 10006

```
>>> geo=g['1b'](house_number='33-33', street_name='broadway', zip_code='11238')
>>> geo.get('ZIP Code', '')
'11249'
>>>
```
Indeed this time it returned a different Brooklyn zipcode. 
I guess it's just something people should keep in mind

**Comment by docmarionum1** [comment]
I think what's happening is twofold:
- As you said, Geosupport is just using the zipcode as an alternative to borough. It doesn't actually try to find the address in _that_ zipcode.
- You're putting a hyphen into address that shouldn't have one. In Manhattan and Brooklyn, a hyphen gets interpreted as a range of addresses. So, 33-33 is from 33 Broadway to 33 Broadway, which has a different zip code but the same borough.

See: https://nycplanning.github.io/Geosupport-UPG/chapters/chapterV/section02/
