### ISSUE TITLE
adding fips into the BOROUGH look up dictionary

### ISSUE THREAD

**Issue by SPTKL** [ishiland/python-geosupport#19]
Should we add FIPS in the BOROUGH look up so people who work with census data can have an easier time? 

36005 - Bronx
36047 - Kings (Brooklyn)
36061 - New York (Manhattan)
36081 - Queens
36085 - Richmond (Staten Island)

Also proposing to add the strange DOE public school Borough prefixes: 
K = Brooklyn (Kings County)
M = Manhattan 
Q = Queens 
R = Staten Island (Richmond County)
X = Bronx

**Comment by ishiland** [comment]
I think this should be OK.  Feel free to make the PR, thanks.
