### ISSUE TITLE
Initializing Geosupport

### ISSUE THREAD

**Issue by ray-phelps** [ishiland/python-geosupport#30]
I have both Python 3.11 (64 bit) and Geosupport version 19b (64 bit) for windows on my computer. My path the environmental variables appear to be correct, I have the fls directory at C:\Program Files\Geosupport Desktop Edition\fls and the bin directory at C:\Program Files\Geosupport Desktop Edition\bin. 

However, when running the code to initialize Geosupport, I get following error message: 
geosupport.error.GeosupportError: Could not find module 'NYCGEO.dll' (or one of its dependencies). Try using the full path with constructor syntax.
You are currently using a 64-bit Python interpreter. Is the installed version of Geosupport 64-bit?

**Comment by ishiland** [comment]
This appears to be some compatibility issue with the latest versions of Geosupport on Windows. Explicitly setting the full path to the `nycgeo.dll` gets past this error but there are some test failures.
