### ISSUE TITLE
GeoSupport 64-BIT NYCGEO.dll not detected

### ISSUE THREAD

**Issue by RaphCodec** [ishiland/python-geosupport#33]
Hi,

I have python 3.8.10 64-BIT and GeoSupport Desktop 64-BIT (gde_23d_x64)  installed.  I have been trying to quickstart code but I keep getting the following error:

geosupport.error.GeosupportError: Could not find module 'NYCGEO.dll' (or one of its dependencies). Try using the full path with constructor syntax.
You are currently using a 64-bit Python interpreter. Is the installed version of Geosupport 64-bit?

I have tried specifying the path to my GeoSupport as seen in the below code but results in the same error. I also tried specifying the path to NYCGEO.dll directly and the same thing occured. Any idea on what the issue may be? 

```
# Import the library and create a `Geosupport` object.
from geosupport import Geosupport
g = Geosupport(geosupport_path="C:\\Program Files\\Geosupport Desktop Edition")

# Call the address processing function by name
result = g.address(house_number=125, street_name='Worth St', borough_code='Mn')
```

**Comment by ishiland** [comment]
Can you try to install python-geosupport from the main branch? I think [this PR](https://github.com/ishiland/python-geosupport/pull/32) will address this issue.

**Comment by RaphCodec** [comment]
That fixed the issue. Thank you very much.
