### ISSUE TITLE
Interactive help string formatting issue

### ISSUE THREAD

**Issue by ishiland** [ishiland/python-geosupport#6]
Line breaks are not working in the interactive help function. 

Issue is reproducible using Win7/Python 3.4 in both Powershell and the Command prompt.

**Comment by docmarionum1** [comment]
Is it showing up with the line breaks in the string? 

Something like:

```
"List of functions (and alternate names):\n1 ()\n1A ()\n1B (address)\n1E ()\n1N (street_name_to_street_code, get_street_code)\n2 (intersection)\n2W (intersections, intersection_wide)\n3 (street_segment)\n3C (blockface)\n3S (street_stretc
h)\nAP (address_point)\nBB (browse_back)\nBF (browse_forward)\nBL (bbl, tax_lot, lot)\nBN (bin, building)\nD (get_street_name)\nDG ()\nDN ()\nN* (normalize_street_name)\n\nCall a function using the function code or alternate name using G
eosupport.<function>() or Geosupport['<function>']().\n\nExample usage:\n    from geosupport import Geosupport\n    g = Geosupport()\n    # Call address using the alternate name.\n    g.address(house_number=125, street_name='Worth St', b
orough_code='Mn')\n    # Call function 3 using the function code.\n    g['3']({'borough_code': 'MN', 'on': '1 Av', 'from': '1 st', 'to': '9 st'})\n\nUse Geosupport.help(<function>) or Geosupport.<function>.help() to read about specific f
unction."
```

If so, it's because the function just returns the string instead of printing it.

Calling print(geosupport.help()) displays it correctly for me.

**Comment by docmarionum1** [comment]
I wonder if it's possible to detect when whether a user is on the command-line/in a jupyter notebook and change it to print automatically? 

I agree, I find it annoying that when I'm using it, it will not display correctly unless I use `print`.  But I didn't want to make it impossible to use the help programatically. 

Maybe printing by default but having a parameter to return instead?

```
def help(return_as_string=False):
    if return_as_string:
       return ...
    else:
        print(...)
```
